### ISSUE TITLE
libSystem.Native disappears when NetBeauty2 is invoked for non-Windows platforms

### ISSUE THREAD

**Issue by s5bug** [nulastudio/NetBeauty2#30]
Without NetBeauty2:

![image](https://user-images.githubusercontent.com/7751296/159812672-4b36f150-9438-4d2d-9cd4-7163942453dc.png)

With NetBeauty2:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Win32, Version=0.10.13.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. Could not find the specified DllImport Dll.
File name: 'Avalonia.Win32, Version=0.10.13.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Native, 0x0001): tried: 'liblibSystem.Native' (no such file), '/usr/local/lib/liblibSystem.Native' (no such file), '/usr/lib/liblibSystem.Native' (no such file), '/Users/#####/Downloads/emufish-osx-arm64-self-contained/liblibSystem.Native' (no such file)
   at Interop.Sys.LStat(Byte& path, FileStatus& output)
   at Interop.Sys.LStat(ReadOnlySpan`1 path, FileStatus& output)
   at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath, ErrorInfo& errorInfo)
   at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath)
   at System.IO.File.Exists(String path)
   at NetBeauty.NBLoader.ManagedAssemblyResolver(AssemblyLoadContext context, AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
fish: Job 1, './EmuFish' terminated by signal SIGABRT (Abort)
```

![image](https://user-images.githubusercontent.com/7751296/159812806-4e70ddf8-2867-4b47-872f-ae07ce45a0a2.png)

**Comment by s5bug** [comment]
![image](https://user-images.githubusercontent.com/7751296/159840755-ebdf7159-8f81-47d7-b222-f1c39b31f51d.png)

Same issue happens on Linux.
